[package]
name = "JA2-MakeSTI"
version = "0.1.0"
authors = ["Asdow <20314541+Asdow@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "0.17"
